export const userData = [
  {
    name: "Dec",
    "Active User": 4279,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Jan",
    "Active User": 3236,
    pv: 1398,
    amt: 2210,
  },
  {
    name: "Feb",
    "Active User": 2150,
    pv: 9800,
    amt: 2290,
  },
  {
    name: "Mar",
    "Active User": 4780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "Apr",
    "Active User": 2890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "May",
    "Active User": 4350,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "Jun",
    "Active User": 3470,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Jul",
    "Active User": 6173,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Aug",
    "Active User": 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "Sep",
    "Active User": 2952,
    pv: 4300,
    amt: 2100,
  },
];

export const userRows = [
  {
    id: 1,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 3,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 4,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 5,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 8,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 9,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "John Snow",
    avatar: "https://picsum.photos/id/338/200/300",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 2,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 3,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 4,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 5,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 6,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 7,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 8,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 9,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 10,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: 123,
    status: "active",
    price: "$120.00",
  },
];

export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 5000,
  },
];


export const staffData = [
  {
    id: 1,
    name: "Zakir Shukurlu",
    img: "/images/z.png",
    title: "Founder & CEO",
  },
  {
    id: 2,
    name: "Martina Malone",
    img: "/images/b.jpeg",
    title: "UX/UI Designer",
  },
  {
    id: 3,
    name: "Leanne Barron",
    img: "/images/a.jpg",
    title: "Software Engineer",
  },
  {
    id: 4,
    name: "Susana Underwood",
    img: "/images/d.jpeg",
    title: "Graphic Designer",
  },
  {
    id: 5,
    name: "Mitch Chandler",
    img: "/images/c.jpeg",
    title: "Software Engineer",
  },
  {
    id: 6,
    name: "Jamie Ellis",
    img: "/images/g.jpeg",
    title: "Data Analyst",
  },
  {
    id: 7,
    name: "Rudolf Hudson",
    img: "/images/e.jpeg",
    title: "DevOps Engineer",
  },
  {
    id: 8,
    name: "Ryan Bridges",
    img: "/images/f.jpeg",
    title: "Cyber​​Security Specialist",
  }
]